### ISSUE TITLE
Release 2.6.0 🗺 Know more about your friends 🙎‍♂️🙎‍♀️

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#1085]
# Release Notes

### ✨🗺  Features

- [x] Peers page highlights peers on your local network (#1266)
- [x] Peers page highlights peers on networks near you (#1266)
- [x] Peers page highlights peers with a low ping time

### 🛠 Fixes and Maintenance

- [x] Peers page performance improvements (#1262)

# Before Release

- [x] Make sure i18n is updated (`tx pull -a`)
- [x] Update Release Notes accordingly

# After Release

- [x] Copy the notes above to the GitHub release
- [x] Update Hash:
   - [x] [`js-ipfs`](https://github.com/ipfs/js-ipfs/blob/master/src/http/api/routes/webui.js#L20)
   - [x] [`go-ipfs`](https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go#L4)
   - [x] [`ipfs-companion`](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/add-on/src/lib/state.js#9)
   - [x] [`ipfs-desktop`](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/package.json#L19)

**Comment by lidel** [comment]
I agree additional indicator would just introduce noise. 
(Peers already higlight low latency peers by defaulting to sort by latency column)

Let's mark it as done. If you want to add something in its place, perhaps `Peers page highlights peers added manually` ?
