### ISSUE TITLE
Release 2.5.1 🛠 Fixes

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#1111]
# Release Notes

### 🛠 Fixes and Maintenance

- [x] Update Dependencies and enable Dependabot (#1083)
- [x] Fix padding in experiments section (#1107)
- [x] Fix Explore bar help text (#1106)
- [x] Add documentation link to config page (#1110)
- [x] Do not assume all nodes are `unixfs` (#1095)
- [x] Allow to use top bar to Explore on IPLD (#1114)
- [x] Stop crashing pin screen on a single `ipfs.files.stat` error (#1121)
- [x] Better distinguishment between links and non-links on Files Page (#1128)

# Before Release

- [x] Make sure i18n is updated (`tx pull -a`)
- [x] Update Release Notes accordingly

# After Release

- [x] Copy the notes above to the GitHub release
- [x] Update Hash:
   - [x] [js-ipfs](https://github.com/ipfs/js-ipfs/blob/master/src/http/api/routes/webui.js#L20) [PR](https://github.com/ipfs/js-ipfs/pull/2434)
   - [x] [go-ipfs](https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go#L4) [PR](https://github.com/ipfs/go-ipfs/pull/6630)
   - [x] [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/add-on/src/lib/state.js#L27) [PR](https://github.com/ipfs-shipyard/ipfs-companion/pull/752)
   - [x] [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/package.json#L17) [PR](https://github.com/ipfs-shipyard/ipfs-desktop/pull/1088)

**Comment by hacdias** [comment]
I feel like this patch release is ready to go! As a patch release, we only have fixes to ship.

Here's the link of the latest build: https://ipfs.io/ipfs/QmQn7B9nLDXgDWjVjgjHActHDQ3AK1NRv7f733P8ki7dik

As per #1129, @olizilla @ericronne @cwaring, I'd like to know if there's something  you think we should change before releases this patch release! 

We've went through the issues talked about on the call two weeks ago

**Comment by hacdias** [comment]
I want to cut a release of Web UI this week! @olizilla @ericronne @cwaring do any of you have time to take a look at Web UI with me to see if there are any major UX things we should change before the release? Remember this is just a patch release for fixes mainly.

**Comment by ericronne** [comment]
I shall make time for This Thing!

Blocked an hour later today ✊

**Comment by hacdias** [comment]
> Blocked an hour later today ✊

@ericronne can we schedule this on a calendar, maybe tomorrow? I won't be available after today's weekly sync 😞

**Comment by ericronne** [comment]
I meant that i blocked time for me to check it out async, so no worries!

**Comment by ericronne** [comment]
Local daemon issues prevent a thorough check for me, sigh. @olizilla assist during our 1:1 tomorrow? 🙏

**Comment by hacdias** [comment]
Any updates on this?

**Comment by ericronne** [comment]
Sussed out the local machine, thx @olizilla!

- The experiments content does not show for me (IPFS Config immediately follows Analytics on settings page)
- I agree with @olizilla ([comment](https://github.com/ipfs-shipyard/ipfs-webui/pull/1114#issuecomment-521964718)) that the combo browse / explore feature likely presents usability issues. Will be interesting to see how users in the wild react to it (ie go ahead and 🚀it), but this is a nice problem to attack with a design workshop soon
- Your design update to the info block strikes me as more user friendly and informative. Underlining `files` and `pins` helps a lot, and the home icon seemed confusing.

Good work @hacdias

**Comment by hacdias** [comment]
> The experiments content does not show for me (IPFS Config immediately follows Analytics on settings page)

Were you using with IPFS Desktop? If not, that's the reason why. Right now, we only have one experiment and it only works with IPFS Desktop.

---

Anyway, thanks for the review. Let me know if you want to check the experiments section before I release 2.5.1!

**Comment by ericronne** [comment]
Ah. Was testing the webui. I don't need to review that bit. Thanks again! 🚢

**Comment by hacdias** [comment]
Thanks @ericronne!

2.5.1 shipped! 🚢
