### ISSUE TITLE
Release 2.5.4

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#1195]
# Release Notes

### 🛠 Fixes and Maintenance

- [x] Show full address when hovering over connectivity (#1169)
- [x] Show all protocols in connectivity (#1167)
- [x] Correctly highlight `p2p-circuit` addresses (#1168)
- [x] Improve address highlight overall (#1188)
- [x] Show full location when hovering over location cell (#1189)

# Before Release

- [x] Make sure i18n is updated (`tx pull -a`)
- [x] Update Release Notes accordingly

# After Release

- [x] Copy the notes above to the GitHub release
- [x] Update Hash:
   - [ ] js-ipfs https://github.com/ipfs/js-ipfs/blob/master/src/http/api/routes/webui.js#L20
   - [ ] go-ipfs https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go#L4
   - [ ] companion https://github.com/ipfs-shipyard/ipfs-companion/blob/master/add-on/src/lib/state.js#L27
   - [ ] desktop https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/package.json#L17
