### ISSUE TITLE
File Browser Revamp

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-webui#704]
### Tasks

- [x] #669 Add files
- [x] #703 Add folder
- [x] #705 Clickable icons 
- [x] #708 Add by IPFS Path
- [x] #709 Make dropdown more similar to [Invision design](https://projects.invisionapp.com/d/main/default/#/console/13924274/302170315/preview)
- [x] #713 Fix error: select files and click another folder
- [x] #714 Validate renaming
- [x] #717 Truncate text
- [x] #718 File Status (Postponed due to DHT api)
- [x] #719 Use pull streams; see https://github.com/ipfs-shipyard/ipfs-webui/pull/703#discussion_r199892990
- [x] #720 Context Menu
- [x] #721 Option to create a new folder
- [x] #723 Merge status with peers column
- [x] #723 Add hash below name 
- [x] #723 Progress on adding files/folders
- [x] #729 Drag'n'drop files
- [x] #736 Error feedback
- [x] Fix https://github.com/ipfs-shipyard/ipfs-webui/pull/736#issuecomment-408360348

### Notes

> From @lidel on #691 (comment):
>
> > ps . Idea for separate PR: I feel we are lacking some kind of visual feedback for user when the button/icon is clicked (fade-out+fade-id of the icon alone, or maybe other way around, making svg stroke more vibrant?).
>
> @fsdiogo: Agree, we should have some feedback while hovering too!
