### ISSUE TITLE
v2.4.0 Release - 📂✨

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#927]
## Improving the file manager 📂✨

- [x] Show loading indicator where `ls` takes longer than 1s (https://github.com/ipfs-shipyard/ipfs-webui/issues/926)
- [x] Lazy render the directory listing to improve rendering perf for large directory listings. (https://github.com/ipfs-shipyard/ipfs-webui/issues/856)
- [x] Show file actions on the file preview page (https://github.com/ipfs-shipyard/ipfs-webui/issues/813)
- [x] Show file actions on right click on a file item in the dir listing (https://github.com/ipfs-shipyard/ipfs-webui/issues/917)
- [x] Increase file-drop area to entire window (https://github.com/ipfs-shipyard/ipfs-webui/issues/916)
- [x] Improve add file flow (the current add to IPFS drop down is confusing)
- [x] Improve create folder flow (https://github.com/ipfs-shipyard/ipfs-webui/issues/915)
- [x] Improve import / pin from IPFS path flow

## Other improvements

- [x] Add self-hosted usage analytics (https://github.com/ipfs-shipyard/ipfs-webui/issues/774 and https://github.com/ipfs/ipfs-gui/issues/72)
- [x] fix mixed content warnings where webui is hosted on a domain (https://github.com/ipfs-shipyard/ipfs-webui/issues/925)

**Comment by fsdiogo** [comment]
🚢 Shipped in [v2.4.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.0) release.
