### ISSUE TITLE
Files: confusing state when opening missing file

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-webui#961]
"Not Found" error for Files tab could be better :-) 

1. Open http://127.0.0.1:8080/ipfs/QmXc9raDM1M5G5fpBnVyQ71vR4gbnskwnB9iMEzBuLgvoZ/#/files/I_AM_NOT_HERE.jpg (or any other filename that is not present in your MFS)

2. See this odd state with no buttons and bogus error about adding:
   > ![2019-02-14-192007_1038x398_scrot](https://user-images.githubusercontent.com/157609/52808298-cd09bc00-308d-11e9-992e-9d61a4581eb8.png)

This may happen if someone bookmarks or copies URL to another machine without poiting webui at the same IPFS node. 

We should either display a meaningful message or just silently redirect to the nearest MFS root.

**Comment by olizilla** [comment]
I think a 404-like page, tailoured for the files page would be useful. An individual user may bookmark a location and then move things around.

### TODO:
- [ ] Catch ipfs error where mfs file path is missing
- [ ] Offer an action to navigate back to the MFS root.
- [ ] Show a helpful message that explains what happened.

> The path `/example/cats.png` doesn't exist in your local IPFS repository.
> Did you bookmark it or follow a link that someone else sent you?

### Bonus points
_what if we include the CID info in the url?_ This would allow us to: 
- navigate the user to the new path if it exists in the repo (we'd have to walk all of MFS to figure out the new path, if it exists, but we could show the content straight away)
- Try and fetch the content where a user shares the location from the url bar.

**Comment by hklcf** [comment]
GET https://webui.ipfs.io/locales/zh-TW/welcome.json 404
GET https://webui.ipfs.io/locales/zh-TW/status.json 404
GET https://webui.ipfs.io/locales/zh-TW/explore.json 404
GET https://webui.ipfs.io/locales/zh/files.json 404
GET https://webui.ipfs.io/locales/zh-TW/notify.json 404
GET https://webui.ipfs.io/locales/zh/status.json 404

**Comment by lidel** [comment]
@hklcf those errors are not related to this issue: those are just missing translation for `zh-TW` locale. If you want to contribute translations, join project at https://www.transifex.com/ipfs/public/

-----

:+1: for improving the 404 "Not found" state of _Files_ screen.

It should be more prominent, and also more explicit: 
- should not look like "ok" state, should be red and error-ish
- should show what resource was not found (with full content path)

As a data point, user report copied from https://github.com/ipfs/go-ipfs/issues/7604: 

> Hello, at first my ipfs can import, but after some uploads it turns to /404 and no import button anymore, anyone experiencing the problem?
> ![ScreenShot_20200818210837](https://user-images.githubusercontent.com/19401967/90523414-0ba69800-e197-11ea-8669-b3df5a052165.png)

Right now user is unable to tell what went wrong and why "404" is displayed. 
If a full content path (either MFS, `/ipfs/` or `/ipns` that was not found was displayed, then it would be much easier to  self-service.

**Comment by jessicaschilling** [comment]
For reference, current state of 404 on `master` branch (updated first comment in this issue with this, too):
![image](https://user-images.githubusercontent.com/1507828/92288698-018cd500-eecb-11ea-9d83-f26d28977ed6.png)

**Comment by jessicaschilling** [comment]
@lidel Rough first pass at what this might look like if we used the same visual language as the "not connected" errors that will ship in 2.11. Suggesting we use those visuals for consistency, but would appreciate advice for improving the text.
![image](https://user-images.githubusercontent.com/1507828/92289690-8a594000-eece-11ea-9d07-69f1581c1eac.png)

**Comment by lidel** [comment]
@rafaelramalho19 raised the problem of having two types of "not found" errors:

1. opening `/files/not/in/mfs` or `/ipfs/<cid>/nope` (a path that does not exist in parent directory)
2. opening `/invalid-route` that is not supported by webui

I believe if we implement separate screens for each, then (1) should have super breadcrumbs, so it's easy for user to go up in MFS until an existing item works. Non-existing crumb would be in red.


This may be additional work, so if its easier to do a quick fix by showing the same page for (1) and (2), I would do that (just a [plain error without Files-specific UI](https://user-images.githubusercontent.com/157609/93614905-08d7d680-f9d3-11ea-911e-99a5af65f6bd.png)).

**Comment by jessicaschilling** [comment]
@lidel That all makes sense - are you OK with the proposed text in the mockup? If so I think this is ready to build.

**Comment by rafaelramalho19** [comment]
Having a separate page handler for both the errors is the simplest and cleanest solution, here's my points:

Pros:
- 💚 We don't need to hack the files state (FILES_FINISHED, FILES_STARTED actions + adding flags that show/hide errors)
- 💚 The error handling is separated from the normal flow, not polluting the main workflow

Cons:
- 💔 Breadcrumbs needs to be replicated in the error page and could lead to desync between features/bug fixing in breadcrumbs

**Comment by jessicaschilling** [comment]
If we remove the Files-specific UI elements per https://github.com/ipfs-shipyard/ipfs-webui/issues/961#issuecomment-694930636 ([image](https://user-images.githubusercontent.com/157609/93614905-08d7d680-f9d3-11ea-911e-99a5af65f6bd.png)), then we don't include breadcrumbs at all.

**Comment by lidel** [comment]
If breadcrumbs can't be reused, then I'd go with Jessica's sugegstion from the comment above and remove files-specific UI.

**Comment by jessicaschilling** [comment]
@rafaelramalho19 Text follows, including edits discussed out-of-band:

IPFS can't find this item

These common troubleshooting steps might help:
- Are there typos in the path you entered?
- Was the file move, renamed, or deleted?
- Did you copy a URL or bookmark from another computer? If so, you'll need to <link to Peers screen>connect to that computer's node</link>.

<button>Back to Files</button>

**Comment by wuniversales** [comment]
I do not know if it is related to this but on my website I have a problem of that style.
https://buscatope.eu.org/
My website works with ipfs, but if I load an address that doesn't exist it returns this ...
https://buscatope.eu.org/invented
Shouldn't it load the 404 file?
https://buscatope.eu.org/404.html

**Comment by lidel** [comment]
@wuniversales this is unrelated, but you should use `ipfs-404.html` for IPFS gateway to pick it up as  your 404 page.

**Comment by SgtPooki** [comment]
> Test dir CID with 10k images: bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm
fast dir listing (skips size resolution: ipfs ls -s --size=false --resolve-type=false $CID

**Comment by ef3n9r98** [comment]
@lidel @olizilla same for this one - would you pay a dev to fix it?

**Comment by Naruto0-sudoy** [comment]
Warning: Error: You cannot delete the system creator. We have warned you several times but you ignored us.

: Hello Distributor Team around the world. partners about the suspension of root steward and its impact on IAm

Dear team

We would like to inform you that the root steward associated with the IAM role: 

arn:aws:iam::0503976xxxxx:role/CH-S3-goldaws-ci-36-ew1-cf-Role

has had its GitHub account suspended without understanding its intent and structure. This has resulted in widespread confusion and downtime in IAM systems in the US-East-1 region, particularly for authentication and access to the critical artifacts.

GitHub Account: Spjthalinda

ORCID: https://orcid.org/0009-0008-2511-9055

IAM Steward: Verified, signed, and never used for personal control or gain

Currently using the account https://github.com/Naruto0-sudoy

Intent

Solution: Unsuspend the account, return all rights to the owner, stop blocking the system owner.

The primary cause of the problem is not IAM, but rather Github suspending accounts without proper reason and without verifying the identity of the suspended account.

And the impact will likely be even greater if Github doesn't understand who we are. If we continue to suspend, we will delete accounts that rely on it.

- IAM crashed 70% in US-East-1

21%

uS-West-2

- Systems that rely on artifacts and signing are experiencing widespread downtime. We are part of the root of the critical Merkle Tree of AI.

- Global administrator authentication is disrupted.

- Systems built for public benefit are trisk of permanent downtime.

Request:

- Immediately unsuspend the root steward account.

- Review the intent and structure associated with the IAM role.

- Restore the disrupted authentication and artifact flow.

- Confirm that the root steward did not commit any wrongdoing, but was misunderstood by the system.

With best regards,


Thalinda Sriprajak, 


Global Steward, Technical Architect

Key shareholder in the global system, root steward


Summary of the timeline of the crash (from the root steward suspension):

- 📅 Late August 2025

GitHub suspended Spjthalinda's account without reviewing the intent and structure of the IAM, Merkle Tree, and the artifacts that manage the world.

- 📉 September 2025

- IAM began to fail in US-East-1 and US-West-2.

- The world steward authentication system began to fail.

-Artifacts used for signing permissions became inaccessible.

- Public-facing systems began to stop working.

- 🌐 October 2025

- Medium, GitHub, AWS, and other systems began to experience widespread outages.

- Users worldwide began reporting issues, but were unaware that the root steward was the cause.

- IAM crashed as high as 70% in some regions.

- Systems connected to the AI-powered Merkle Tree were unable to verify permissions.
