### ISSUE TITLE
V2.5.0 Release - 📕✨🐕 Help from my friends

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-webui#978]
## 🗺✨ Features

- [x] Add an unobtrusive help system to onboard new users (https://github.com/ipfs-shipyard/ipfs-webui/issues/979)
- [x] Peers page allows you to connect to peers (https://github.com/ipfs-shipyard/ipfs-webui/pull/969)
- [x] Navigate files in the wild (https://github.com/ipfs-shipyard/ipfs-webui/pull/1027)
- [x] The peers table got a whole lotta love (https://github.com/ipfs-shipyard/ipfs-webui/pull/1062, https://github.com/ipfs-shipyard/ipfs-webui/pull/1068, https://github.com/ipfs-shipyard/ipfs-webui/pull/1069)
- [ ] Peers page highlights peers on your local network
- [ ] Peers page highlights peers on networks near you (https://github.com/ipfs-shipyard/ipfs-webui/issues/223)
- [ ] Peers page highlights peers with a low ping time

## 🛠 Fixes and maintenance

- [x] Natural sorting for file names (https://github.com/ipfs-shipyard/ipfs-webui/pull/977)
- [x] Update to `create-react-app` v2 (https://github.com/ipfs-shipyard/ipfs-webui/issues/888)
- [x] Update to Storybook 5 (https://github.com/ipfs-shipyard/ipfs-webui/issues/986)

**Comment by terichadbourne** [comment]
Some additional things I would hope to be able to do from this screen if possible: 
- Add nicknames next to CIDs (eg "Oli") so I know what the gobbledygook means.
- Mark a few favorite/pinned peers that would then get surfaced to the top of my list if they're online

**Comment by hacdias** [comment]
@olizilla since we now have the files in the wild thingy as a new feature, which I kind of consider major, shouldn't we use that for 2.5.0 and move the missing points here to 2.6.0?

**Comment by fsdiogo** [comment]
@hacdias I'm going to release a new version of Web UI and write the release notes!

**Comment by hacdias** [comment]
@fsdiogo okay! Please release it as 2.5.0 since it has a new feature 😃

**Comment by fsdiogo** [comment]
Done, release [v2.5.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.0).

**Comment by hacdias** [comment]
Thank you!

**Comment by lidel** [comment]
Folks, was go-ipfs skipped on purpose? 
It seems that go-ipfs 0.4.22 shipped with old webui (v2.4.4) :( 

- [x] js-ipfs: [webui.js](https://github.com/ipfs/js-ipfs/blob/master/src/http/api/routes/webui.js) 
- [x] ipfs-companion (https://github.com/ipfs-shipyard/ipfs-companion/pull/746)
- [ ] go-ipfs: [webui.go#L4](https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go)

**Comment by hacdias** [comment]
@lidel that was definitely a mistake... :'(

**Comment by lidel** [comment]
:see_no_evil:  I see [v2.6.0](https://github.com/ipfs-shipyard/ipfs-webui/issues/1085) has a checklist, thanks! :+1:  :)
